CREATE TABLE [dbo].[tblCharacterWeapons]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Weapon_Id] UNIQUEIDENTIFIER NOT NULL, 
    [Character_Id] UNIQUEIDENTIFIER NOT NULL, 
    [Equipped] BIT NOT NULL
)
