CREATE TABLE [dbo].[tblCharacterCurrency]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Currency_Id] UNIQUEIDENTIFIER NOT NULL, 
    [Character_Id] UNIQUEIDENTIFIER NOT NULL, 
    [Amount] INT NOT NULL
)
