CREATE TABLE [dbo].[tblCharacterClasses]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Character_Id] UNIQUEIDENTIFIER NOT NULL, 
    [Class_Id] UNIQUEIDENTIFIER NOT NULL, 
    [Class_Level] INT NOT NULL
)
